general:
  #python environment to be used when running jobs
  #something that would be activated as:
  # source activate env_name
  conda environment: env_name # or /path/to/env_name
  
  # Default system for job submission.
  # Options:
  #   slurm_cori: Use SLURM on Cori
  #   slurm_perlmutter: Use SLURM on Perlmutter
  #   bash: Run jobs directly in terminal (e.g. login node at NERSC)
  system: slurm_perlmutter

  # general slurm args, e.g. mail options
  slurm args:
    mail-type: fail
    mail-user: user@host.com

  defaults file: # Use a defaults file like Y1v7
  # defaults locaed in picca_bookkeeper/resources/default_configs

data:
  # Parent path of the bookkeeper, where outputs will go.
  bookkeeper dir: /desired/output/path/

  healpix data: /global/cfs/cdirs/desi/spectro/redux/iron/healpix/

  catalog: /global/cfs/cdirs/desicollab/science/lya/y1-kp6/iron-tests/catalogs/QSO_cat_iron_main_dark_healpix_zlya-altbal_zwarn_cut_20230918.fits



delta extraction:
  # If full delta extraction already computed can use this to always point to it
  # use existing: /path/to/bookkeeper (bookkeeper folder)
  # (then pass --skip-sent option in terminal)

  # Calibration mode for delta extraction.
  calib: 0
  # Options:
  #   0: No calibration (default, just run extraction)
  #   1: Apply calibration from a previous run (single step)
  #   2: Two-step calibration (calibration and IvarCorrection)
  #   3: Special calibration mode (see Bookkeeper docs/code)
  #   10: User provides all calibration corrections manually
  # If using 2, you may need to specify calibration data paths below.

  # Calibration region to use, e.g. mgii_r, lya, etc.
  calib region: mgii_r
  # Only needed if calib != 0.
  
  dla: /path/to/dla_catalog
  # If added, DLAs will be masked automatically
  bal: /path/to/bal_catalog
  # If added, BALs selected from added catalog, if True BALs from data/catalog above

 # Optional: Path to a line mask file for delta extraction.
  mask file: # Add a line mask file
  # e.g. /.../desicollab/science/lya/y3/loa/deltas/delta-lya-2-0/continuum_fitting_mask.txt

  # Only if you want to re-use calibration data from a different analysis.
  # Insert here the path of a delta-attributes.fits.gz file to use it as 
  # calibration data for the current run.
  calibration data:
    step 1:
    step 2: # leave this empty if only 1 step calib.

  # Optional: Use precomputed deltas from another location.
  # Insert here the parent folder containing both Delta and Log folders. 
  # Keys:
  #   general: Path with all deltas
  #   lya: Path for Lyman-alpha region deltas
  #   <region>: Path for other regions as defined in forest_regions (e.g. ciii)
  computed deltas:
    # general: /path/to/deltas/results
    # lya: /path/to/deltas/results/lya
    
  # extra args to be used by the bookkeeper
  # match the section name with the name of the scripts under picca.bin
  # You can set general options, or override per region (e.g. ciii, lya).
  # To remove an option, set its value to '$' (see fits.extra args section for example).
  extra args:
    picca_delta_extraction:
      # Default value for all regions
      general:
        expected flux:
          type: Dr16FixedFudgeExpectedFlux 
          fudge value: 0 # This to deactivate fudge.
        data:
          wave solution: lin # Example, wave solution already lin by default (options: lin, log, etc).


      # To affect a specific region (must match region names in Bookkeeper.forest_regions):
      # The values set here will extend the ones defined in picca_delta_extraction
      ciii: # e.g. for the ciii region only.

      # To force the change even if there are specific defaults for some regions
      # in the default config file, use all regions
      # "all:"

    # Scripts with terminal argumentss are also compatible
    picca_convert_transmission:
      general:
        nspec: 30
        # use-splines: ""# use empty string for action args like no-project.

    
  # Slurm arguments to be used by the bookkeeper
  slurm args:
    general:
    
    picca_delta_extraction:
      general:
        time: "00:16:00"
        qos: debug

correlations:
  # If full correlations already computed can use this to always point to it
  # if in use, this should be the only key and everything else should be
  # commented out or removed
  # use existing: /path/to/bookkeeper (bookkeeper folder)

  # tracer catalogs could be set up to use a different catalog for cross-correlations
  # by default will use data:catalog for the qso tracer.
  #tracer catalogs:
  #  qso: 

  # Unblind correlations. Only use this if you are allowed to!
  unblind: False
  unblind y1: False

  # whether to use the new fast_metals code
  fast metals: True

  computed correlations:
    # general: /path/to/correlations/results
    # lyalya_lyalya: /path/to/correlations/results/lyalya_lyalya/cf.fits
    # qso_lyalya: /path/to/correlations/results/lyalya/xcf.fits

  computed exports:
    # general: /path/to/correlations/results
    # lyalya_lyalya: /path/to/correlations/results/lyalya_lyalya/cf_exp.fits
    # qso_lyalya: /path/to/correlations/results/lyalya/xcf_exp.fits
  
  computed distortions:
    # general: /path/to/correlations/results
    # lyalya_lyalya: /path/to/correlations/results/lyalya_lyalya/dmat.fits
    # qso_lyalya: /path/to/correlations/results/lyalya/xdmat.fits

  computed metals:
    # general: /path/to/correlations/results
    # lyalya_lyalya: /path/to/correlations/results/lyalya_lyalya/metal.fits
    # qso_lyalya: /path/to/correlations/results/lyalya/xmetal.fits

  extra args:
    picca_cf:
      general:
        nside: 16
        # no-project: "" # use empty string for action args like no-project.

      # To affect an specific region use the following format
      # remember fo follow the region names in picca_bookkeeper.Bookkeeper.forest_regions
      # The values set here will overlap the ones defined in picca_cf, so both will be applied
      lyalya_lyalya:

      # lyalyb: Lyman alpha in the lyman beta forest.
      lyalya_lyalyb:

    picca_xcf:

    # For the cross we use qso_lyalya format.
    picca_xcf:
        qso_lyalya:

    picca_dmat:

    picca_xdmat:

    picca_metal_dmat:

    picca_metal_xdmat:

    picca_export:

  slurm args:
    picca_cf:
      general:
        #

fits:
  # This is the user-friendly name for the fit run
  run name: default

  # Add covariance matrix options
  compute covariance: False
  smooth covariance: False

  # Either provide general or both smoothed and full.
  computed covariances: 
    # general: /path/to/fits/results
    # full-covariance: /path/to/fits/results/full-covariance.fits
    # full-covariance-smoothed: /path/to/fits/results/full-covariance-smoothed.fits

  # These are the correlations to use. If running the full analysis, 
  # the correspondent deltas and correlations will be computed
  auto correlations: lya.lya-lya.lya lya.lya-lya.lyb
  cross correlations: qso-lya.lya 

  # Whether to use a different environment for sampler. If empty, the general
  # environment will be used. The one below is mantained by Andrei Cuceu.
  sampler environment: /global/common/software/desi/users/acuceu/stable_vega/activate_vega.sh

  # If we want to compute zeff right before the fit
  compute zeff: True

  # If we want Vega to compute metals:
  vega metals: False

  
  # Remove some fit options
  no distortion: False # Whether to use distortion matrix
  no bao: False
  no hcd: False
  no metals: False
  no sky: False
  no qso rad: False

  rmin cf:
  rmax cf: 
  rmin xcf:
  rmax xcf:


  # To use same functions we call this extra_args although vega is used.
  extra args:
    vega_auto:
      data:
        tracer1-type: continuous
    # include the following to only run A region, and exclude B region
    # defualt: auto auto cross cross (lyaxlya, lyaxqso, lyaxlyb, lybxqso)
    smooth_covariance:
      general:
        block-types: auto cross

    vega_auto:
      general:
      
      lyalya_lyalya:

    vega_cross:
      general:

      qso_lyalya:

    vega_main:
      general:

  ## It is possible to remove certain configuration parameters using the extra 
  ## args section. For this, we use $ in the following way:
  # exta args:
  #   vega_main: 
  #     all: # you can remove from general, specific regions or everywhere with "all"
  #       sample:
  #         ap: $
  #         at: $
    
  slurm args:
    run_vega: # minimizer args
      general:
        qos: shared
        ntasks-per-node: 1
        cpus-per-task: 8
        OMP_NUM_THREADS: 1

    run_vega_mpi: # sampler args
      general:
        nodes: 2
        ntasks-per-node: 128 # Use always per-node within the bookkeeper!
        
#################################################################################

# Command-line override options #
# ----------------------------- #
# note: these are not .yaml options, but are useful for submitting from the terminal
#       e.g. "picca_bookkeeper_run_full_analysis /path/to/config --[args]"
#
#   --system <name>        : Override system for this run.
#   --region <region>      : Run for specific region (default: 'lya').
#   --overwrite            : Overwrite output data.
#   --overwrite-config     : Overwrite bookkeeper config.
#   --skip-sent            : Skip already-submitted jobs.
#   --debug                : Enable debug mode.
#   --only-calibration     : Only run calibration steps.
#   --skip-calibration     : Skip calibration even if enabled in config.
#   --only-write           : Only write job scripts, don't submit.
#   --wait-for <ids>       : Wait for job IDs before running.
#   --log-level <level>    : Logging verbosity (default: INFO).
