general:
  #python environment to be used when running jobs
  #something that would be activated as:
  # source activate picca
  conda environment: picca
  
  # default system to run bookkeeper on
  # slurm_cori: slurm for cori
  # slurm_perlmutter: slurm for perlmutter
  # bash: run on terminal (login nodes at NERSC)
  system: slurm_perlmutter

  # general slurm args, e.g. mail options
  slurm args:
    mail-type: fail
    mail-user: user@host.com

data:
  # Parent path of the bookkeeper.
  bookkeeper dir: /blabla

  # Hardcode the healpix data location, by default it will be set
  # according to the release, e.g. for everest:
  # /global/cfs/cdirs/desi/spectro/redux/everest/healpix/
  healpix data:

  # The structure of folders and sub-folders is the following:
  # {bookkeeper dir}/{release}/{survey}/{qso_cat}
  # where:
  #   - release (everest, fuji): specifies the version of the pipeline used.
  #   - survey (sv1, sv2, sv3, sv, all, main): specifies the survey (or 
  #           combination of surveys) used.
  #   - qso_cat (redrock_v0, redrock_v1, afterburner_v0, etc): specifiec the
  #           quasar catalog used (containing BAL information).
  release: guadalupe
  survey: main
  # Catalog could be a name (and therefore will be used the bookkeeper one)
  # or could be a full path to a catalog
  catalog: afterburn_v0


delta extraction:  
  # The structure of folders and sub-folders is the following:
  # .../{bookkeeper dir}/{relase}/{survey}/{qso_cat}/{prefix}_{calib}.{calib_region}.{dla}.{bal}_{suffix}
  # where {prefix}_{calib}.{calib_region}.{dla}.{bal}_{suffix} defines the continuum fitting used:
  #   - prefix (dMdB20, CRP23, raw, True): specifies the general configuration of the run.
  #       - dMdB20: fudge included, 2.4A bins, var lss mod=0 (see resources/dMdB20.yaml)
  #       - CRP23: analysis performed for early3D DESI analyses. nofudge, 0.8A bins, var lss mod = 7.5, lambda rest frame max=1205.
  #       - raw: use this for raw mocks.
  #       - true: use this for true continuum analyses.
  #       - Could also match any of the yaml files under picca_bookkeeper.resources.default_configs
  #
  #   - calib (0, 1, 2): Integer defining the number of calibration steps.
  #       - 0: no calibration.
  #       - 1: early3D calibration: One step calibration (flux).
  #       - 2: dMdB20 calibration: Two step calibration (first for flux, second for IVAR).
  #       - 10: Accept custom options for calibration in yaml file.
  #
  #   - calib region (any of the ones defined in picca_bookkeeper.Bookkeeper.forest_regions)
  #         0 if no calibration is used.
  #
  #   - dla (0, 1, 2, etc): integer identifying the version of DLA masking used
  #       - 0: no DLA masking.
  #       - 1: First version of DLA catalog.
  #       - N: Nth version of DLA catalog. 
  #
  #   - bal (0, 1, 2, etc): integer identifying the version of BAL masking used 
  #       - 0: No BAL masking.
  #       - 1: Drop BAL objects (not implemented).
  #       - 2: Mask BAL objects.
  #
  #   - suffix (0, any string): any string identifying anything else particular
  #           in the analysis (0 means nothing). This is free for the user to select
  #           whatever they consider appropiately if it does not overlap with other 
  #           runs

  prefix: dMdB20
  calib: 0
  calib region: mgii_r
  dla: 0
  bal: 0
  suffix: 0

  # Insert here the name of the analysis using the format
  # {prefix}_{calib}_{calib_region}.{dla}.{bal}_{suffix}, e.g: dMdB20_2.ciii.0.0_0
  # in order to use calibration files from there.
  # Leave empty to compute calibration deltas.
  calibration data:
  # line masking to be applied in the continuum fitting process.
  mask file:
  # force DLA catalog (if not the one correspondent to the catalog above will be used)
  dla catalog:
  # force BAL catalog (if not the one corresponent to the catalog above will be used)
  bal catalog:

  # extra args to be used by the bookkeeper
  # match the section name with the name of the scripts under picca.bin
  extra args:
    picca_delta_extraction:
      expected flux:
        type: Dr16FixedFudgeExpectedFlux # This to deactivate fudge.
        fudge value: 0
      data:
        wave solution: lin # This is an example, wave solution is set to lin by default in the bookkeeper.

    # To affect an specific region use 
    # remember fo follow the region names in picca_bookkeeper.Bookkeeper.forest_regions
    # The values set here will overlap the ones defined in picca_delta_extraction
    # for the ciii region only.
    picca_delta_extraction_ciii:

    # Scripts with terminal args are also compatible
    picca_convert_transmission:
      nspec: 30
    # use-splines: ""# use empty string for action args like no-project.

    
  # Slurm arguments to be used by the bookkeeper
  slurm args:
    general:
    
    picca_delta_extraction:
      time: "00:16:00"
      qos: debug

correlations:
  # If a delta extraction is defined in the same config file (as the current one), 
  # this can be left empty. Otherwise, the user should provide the name of the analysis
  # using the format # {prefix}_{calib}.{calib_region}.{dla}.{bal}_{suffix}, 
  # e.g: dMdB20_2.ciii.0.0_0
  delta extraction:

  # This is the user-friendly name for the correlation run+
  run name: default

  # catalog_tracer could be set up to use a different catalog for cross-correlations
  # by default will use the previous one for all the analyses.
  catalog tracer: 

  # copy metal matrices from a different place.
  # For auto-, one should provide the two absorbers and regions
  metal matrices: 
    # Use all to use same matrix for all analyses
    all: 
    # or specify regions/absorbers
    lyalya_lyalya: /global/cfs/cdirs/desicollab/users/cgordon/Y1/bookkeeper_test/iron/main/QSO_cat_iron_main_dark_healpix_v0/dMdB20_2.ciii.1.2_0/correlations/default/correlations/lyalya_lyalya/metal.fits.gz 
    lyalya_lyalyb: /global/cfs/cdirs/desicollab/users/cgordon/Y1/bookkeeper_test/iron/main/QSO_cat_iron_main_dark_healpix_v0/dMdB20_2.ciii.1.2_0/correlations/default/correlations/lyalya_lyalyb/metal.fits.gz 

  xmetal matrices:
    all:
    # For cross-, only one absorber/region is needed.
    lyalya: /global/cfs/cdirs/desicollab/users/cgordon/Y1/bookkeeper_test/iron/main/QSO_cat_iron_main_dark_healpix_v0/dMdB20_2.ciii.1.2_0/correlations/default/correlations/lyalya_qso/xmetal.fits.gz
    lyalyb: /global/cfs/cdirs/desicollab/users/cgordon/Y1/bookkeeper_test/iron/main/QSO_cat_iron_main_dark_healpix_v0/dMdB20_2.ciii.1.2_0/correlations/default/correlations/lyalyb_qso/xmetal.fits.gz


  extra args:
    picca_cf:
      nside: 16
    # no-project: "" # use empty string for action args like no-project.

    # To affect an specific region use the following format
    # remember fo follow the region names in picca_bookkeeper.Bookkeeper.forest_regions
    # The values set here will overlap the ones defined in picca_cf, so both will be applied
    picca_cf_lyalya_lyalya:

    # lyalyb: Lyman alpha in the lyman beta forest.
    picca_cf_lyalya_lyalyb:

    picca_xcf:

    # For the cross we se lyalya format.
    picca_xcf_lyalya:

    picca_dmat:

    picca_xdmat:

    picca_metal_dmat:

    picca_metal_xdmat:

    picca_export:

  slurm args:
    general: 

fits:
  # If a delta extraction is defined in the same config file (as the current one), 
  # this can be left empty. Otherwise, the user should provide the name of the analysis
  # using the format # {prefix}_{calib}_{calib_region}.{dla}.{bal}_{suffix}, 
  # e.g: dMdB20_2.ciii.0.0_0
  delta extraction: 

  # Similarly as before, define a correlation run name if it was not defined above.
  correlation run name:

  # This is the user-friendly name for the fit run
  run name: default

  # To use same functions we call this extra_args although vega is used.
  extra args:
    vega_auto:
      data:
        tracer1-type: continuous

    vega_auto_lyalya_lyalya:

    vega_cross:

    vega_cross_lyalya:

    vega_main:

    ## Uncomment this to remove certain configuration parameters from the fit
    ## This will remove ap and at from sample section in vega main
    # effectively removing BAO fitting
    # remove_vega_main:
    #   sample:
    #     ap:
    #     at:

  # There is only one script (run_vega.py)
  slurm args:
    run_vega:
      mail-type: fail
      mail-user: user@host.com