general:
  conda environment: /global/common/software/desi/users/cramirez/conda/envs/durham2023
  system: slurm_perlmutter

data:
  bookkeeper dir: /path/to/analysis
 
  # Provide custom transmission data (although is likely to be v9.0.x anyway)
  healpix data: /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.0
  
  release: v9.0.0 # This can be anything
  survey: raw
  
  catalog: /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.0/master.fits
  

delta extraction:
  prefix: raw
  calib: 0 # Not implemented for mocks
  dla: 0 # Not implemented for mocks (set to 1 to show 1 in output paths)
  bal: 0 # Not implemented for mocks (set to 1 to show 1 in output paths)
  suffix: 0

  mask file:


correlations:
  run name: default
  # catalog_tracer could be set up to use a different catalog for cross-correlations
  # by default will use the data:catalog one.
  catalog tracer:

fits:
  auto correlations: lya.lya-lya.lya
  cross correlations: lya.lya
  run name: default

  distortion: False
  metals: False