general:
  conda environment: picca_new_cont
  system: slurm_perlmutter

data:
  bookkeeper dir: /path/to/analysis
 
  # Provide custom healpix data folder /../../spectra-16
  # by default it will be defined by release and survey
  # fields below
  healpix data: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/spectra-16
  
  release: iron # This can be anything
  survey: main # This can also be anything
  
  catalog: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/qsocat_iron_main.fits

delta extraction:
  prefix: True
  calib: 0 # Not implemented for mocks
  dla: 1 # Not implemented for mocks (set to 1 to show 1 in output paths)
  bal: 1 # Not implemented for mocks (set to 1 to show 1 in output paths)
  suffix: 0

  # For mocks this can be used to define the full path to the DLA catalog
  dla catalog: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/dlacat.fits
  # The same for BAL catalog
  bal catalog: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/balcat.fits 
  mask file:

  extra args:
      expected flux:
        raw statistics file: #/pscratch/sd/c/cramirez/bkp_mocks/v9.0.0/raw/LyaCoLoRe/raw_0.0.0.0_0/results/lya/Delta-stats.fits.gz

correlations:
  run name: default
  # catalog_tracer could be set up to use a different catalog for cross-correlations
  # by default will use the data:catalog one.
  catalog tracer:

fits:
  auto correlations: lya.lya-lya.lya
  cross correlations: lya.lya
  run name: default

  distortion: False
  metals: False
