general:
  conda environment: /global/common/software/desi/users/cramirez/conda/envs/durham2023
  system: slurm_perlmutter

  slurm args:
    mail-type: fail
    mail-user: user@host.com

  defaults file: raw

  raw mocks: True

data:
  bookkeeper dir: /path/to/analysis
 
  # Provide custom transmission data (although is likely to be v9.0.x anyway)
  healpix data: /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.0
  
  catalog: /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.0/master.fits
  

delta extraction:
  calib: 0 # Not implemented for mocks
  dla: 
  bal: 
  mask file:


correlations:
  # catalog_tracer could be set up to use a different catalog for cross-correlations
  # by default will use the data:catalog one.
  catalog tracer:

fits:
  auto correlations: lya.lya-lya.lya
  cross correlations: lya.lya

  distortion: False
  metals: False