general:
  conda environment: picca_new_cont
  system: slurm_perlmutter

  slurm args:
    mail-type: fail
    mail-user: user@host.com

  defaults file: TrueMocks

  true mocks: True

data:
  bookkeeper dir: /path/to/analysis
 
  healpix data: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/spectra-16
   
  catalog: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/qsocat_iron_main.fits

delta extraction:
  calib: 0 # Not implemented for mocks

  # For mocks this can be used to define the full path to the DLA catalog
  dla: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/dlacat.fits
  # The same for BAL catalog
  bal: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/balcat.fits 
  mask file:

  extra args:
      expected flux:
        raw statistics file: #/pscratch/sd/c/cramirez/bkp_mocks/v9.0.0/raw/LyaCoLoRe/raw_0.0.0.0_0/results/lya/Delta-stats.fits.gz # Needed for true (?)

correlations:

fits:
  auto correlations: lya.lya-lya.lya
  cross correlations: qso-lya.lya

  distortion: False
  metals: False
