general:
  conda environment: /global/common/software/desi/users/cramirez/conda/envs/durham2023
  system: slurm_perlmutter

  slurm args:
    mail-type: fail
    mail-user: user@host.com

  defaults file: quickquasars

data:
  bookkeeper dir: /path/to/analysis
 
  # Provide custom healpix data folder /../../spectra-16
  # by default it will be defined by release and survey
  # fields below
  healpix data: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/spectra-16
    
  catalog: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/qsocat_iron_main.fits
  

delta extraction:
  calib: 0 
  calib region: mgii_r

  # For mocks this can be used to define the full path to the DLA catalog
  dla: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/dlacat.fits
  # The same for BAL catalog
  bal: /global/cfs/cdirs/desicollab/users/hiramk/desi/qq_mocks/iron/main/mock/london/v9.0.0/iron_main-0.134/balcat.fits 
  mask file:


correlations:

fits:
  auto correlations: lya.lya-lya.lya
  cross correlations: lya.lya

  distortion: False
  metals: False