general:
  conda environment: picca
  system: slurm_perlmutter
  
data:
  early dir: /path/to/analysis  
  healpix data:
  release: guadalupe
  survey: main
  catalog: afterburn_v0
   
  
delta extraction:
  prefix: dMdB20
  calib: 1 #dr16 method of calibraiton
  calib region: ciii
  dla: 0
  bal: 2 #bal masking
  suffix: 0

  slurm args:
    general:
      mail-type: fail
      mail-user: xxxxx@yyyyyy.com

correlations:
  run name: default