system:
  conda environment: picca
  system: slurm_perlmutter
  
data:
  early dir: /path/to/analysis  
  healpix data:
  release: guadalupe
  survey: main
  catalog: afterburn_v0
   
  
delta extraction:
  prefix: dMdB20
  calib: 1 #dr16 method of calibraiton
  calib region: ciii
  dla: 0
  bal: 2 #bal masking
  suffix: 0

  slurm args:
    general:
      mail-type: fail
      mail-user: xxxxx@yyyyyy.com
    picca_delta_extraction:
      time: 03:00:00
      qos: regular

correlations:
  run name: default
    
  slurm args:
    picca_cf:
      time: 01:00:00
      qos: regular
    
    picca_xcf:
      time: 01:00:00
      qos: regular
      
    picca_dmat:
      time: 01:00:00
      qos: regular
    picca_xdmat:
      time: 01:00:00
      qos: regular
    picca_metal_dmat:
      time: 01:00:00
      qos: regular
    picca_metal_xdmat:
      time: 01:00:00
      qos: regular
    picca_export:
      time: 00:10:00
      qos: debug

