system:
  picca environment: picca
  system: slurm_perlmutter
  
data:
  early dir: /global/cfs/cdirs/desi/science/lya/early-3d/
  
  healpix data:
  release: guadalupe
  survey: main
  catalog: afterburn_v0
   
delta extraction:
  prefix: dMdB20
  calib: 1
  calib region: mgii_r
  dla: 0
  bal: 0
  suffix: 0

  slurm args:
    general:
      mail-type: fail
      mail-user: user@host.com
    picca_delta_extraction:
      time: 03:00:00
  
correlations:
  run name: default

  slurm args:
    general:
      mail-type: fail
      mail-user: user@host.com