general:
  conda environment: picca_new_cont
  system: slurm_perlmutter

data:
  bookkeeper dir: /path/to/analysis
  input_dir: 
 
  # Provide custom healpix data folder /../../spectra-16
  # by default it will be defined by release and survey
  # fields below
  healpix data: 
  
  # Fill release and survey to get the default healpix data 
  # under /global/cfs/cdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0/{release}/{survey}
  release: v9.0.0
  survey: desi-2.0-1000 # use raw for raw analyses
  
  # LyaCoLoRe to read catalog from healpix data directory
  # custom catalog path for custom catalog
  catalog: LyaCoLoRe
  

continuum fitting:
  # The structure of folders and sub-folders is the following:
  # {bookkeeper dir}/{relase}/{survey}/{qso_cat}/{prefix}_0.0.0_{suffix}
  # where {prefix}_0.0.0.0_{suffix} defines de continuum fitting used:
  #   - prefix (dMdB20, pca, etc): specifies the type of continuum fit
  #        - dMdB20: used in eBOSS DR16, default in picca.
  #        - true: use true continuum branch
  #        - raw: use raw deltas
  #   - suffix (0, any string): any string identifying anythin else particular
  #           in the analysis (0 means nothing).
  prefix: dMdB20
  calib: 0 # Not implemented for mocks
  dla: 0 # Not implemented for mocks
  bal: 0 # Not implemented for mocks
  suffix: 0

  dla catalog: # For mocks this can be used to define the full path to the DLA catalog
  bla catalog: # The same for BAL catalog
  mask file:


correlations:
  run name: default
  # catalog_tracer could be set up to use a different catalog for cross-correlations
  # by default will use the data:catalog one.
  catalog tracer:

