general:
  #python environment to be used when running jobs
  #something that would be activated as:
  # source activate picca
  conda environment: picca
  
  # default system to run bookkeeper on
  # slurm_cori: slurm for cori
  # slurm_perlmutter: slurm for perlmutter
  # bash: run on terminal (login nodes at NERSC)
  system: slurm_perlmutter

  # general slurm args, e.g. mail options
  slurm args:
    mail-type: fail
    mail-user: user@host.com

data:
  # Parent path of the bookkeeper.
  bookkeeper dir: /blabla

  # Hardcode the healpix data location, by default it will be set
  # according to the release, e.g. for everest:
  # /global/cfs/cdirs/desi/spectro/redux/everest/healpix/
  healpix data:

  # The structure of folders and sub-folders is the following:
  # {bookkeeper dir}/{release}/{survey}/{qso_cat}
  # where:
  #   - release (everest, fuji): specifies the version of the pipeline used.
  #   - survey (sv1, sv2, sv3, sv, all, main): specifies the survey (or 
  #           combination of surveys) used.
  #   - qso_cat (redrock_v0, redrock_v1, afterburner_v0, etc): specifiec the
  #           quasar catalog used (containing BAL information).
  release: guadalupe
  survey: main
  # Catalog could be a name (and therefore will be used the bookkeeper one)
  # or could be a full path to a catalog
  catalog: afterburn_v0

fits:
  # Name of delta analysis available under bookkeeper path and data values
  # using the format # {prefix}_{calib}.{calib_region}.{dla}.{bal}_{suffix}, 
  # e.g: dMdB20_2.ciii.0.0_0
  # It will be used to search for the correlations
  delta extraction: 

  # Similarly as before, define a correlation run name
  # Under de specified deltas
  correlation run name:

  # This is the user-friendly name for the fit run
  run name: default

  auto correlations: lya.lya-lya.lya lya.lya-lya.lyb
  cross correlations: lya.lya 

  bao: True
  hcd: True
  metals: True
  sky: True
  qso rad: True
  rmin cf:
  rmax cf: 
  rmin xcf:
  rmax xcf:


  # To use same functions we call this extra_args although vega is used.
  extra args:
    vega_auto:
      data:
        tracer1-type: continuous

    vega_auto_lyalya_lyalya:

    vega_cross:

    vega_cross_lyalya:

    vega_main:

    ## Uncomment this to remove certain configuration parameters from the fit
    ## This will remove ap and at from sample section in vega main
    # effectively removing BAO fitting
    # remove_vega_main:
    #   sample:
    #     ap:
    #     at:

  # There is only one script (run_vega.py)
  slurm args:
    run_vega:
      mail-type: fail
      mail-user: user@host.com