general:
  conda environment: picca
  system: slurm_perlmutter
  
  # general slurm args, e.g. mail options
  slurm args:
    mail-type: fail
    mail-user: user@host.com
  
data:
  bookkeeper dir: /path/to/analysis  
  healpix data:
  release: guadalupe
  survey: main
  catalog: afterburn_v0
   
  
delta extraction:
  prefix: dMdB20
  calib: 1 #EDR method of calibraiton
  calib region: ciii
  dla: 0
  bal: 2 #bal masking
  suffix: 0

correlations:
  run name: default

fits:
  run name: default